### ISSUE TITLE
Disable once comment not analyzed properly

### ISSUE THREAD

**Issue by rsuter** [CSharpAnalyzers/ExceptionalReSharper#14]
The comment is not always correctly analyzed: Sometimes it works sometimes it does not work...

https://exceptional.codeplex.com/workitem/11003

**Comment by pedromagueija** [comment]
@rsuter Same as #37? Perhaps we can close this one as well.

**Comment by rsuter** [comment]
Ok. Should we create a release?

**Comment by pedromagueija** [comment]
Yep, I think we have enough for a release at this point.
