### ISSUE TITLE
not support nameof()

### ISSUE THREAD

**Issue by lotosbin** [CSharpAnalyzers/ExceptionalReSharper#27]
```throw new ArgumentNullException(nameof(transaction));```
generate:
        ```/// <exception cref="ArgumentNullException"><paramref name=""/> is <see langword="null" />.</exception>```

better:
```
  /// <exception cref="ArgumentNullException"><paramref name="transaction"/> is <see langword="null" />.</exception>```

**Comment by rsuter** [comment]
Same as https://github.com/CSharpAnalyzers/ExceptionalReSharper/issues/5

**Comment by pedromagueija** [comment]
There are a couple of cases here:

1. `throw new ArgumentNullException()`
2. `throw new ArgumentNullException("Arg cannot be null", innerException)`
3. `throw new ArgumentNullException(nameof(arg), "Arg cannot be null")` or `throw new ArgumentNullException("arg", "Arg cannot be null")`
4. `throw new ArgumentNullException(nameof(arg))` or `throw new ArgumentNullException("arg")`

Should generate the following documentation:
1. `<exception cref="ArgumentNullException">Thrown when the arguments are <see langword="null"/></exception>`
2. `<exception cref="ArgumentNullException">Arg cannot be null</exception>`
3. `<exception cref="ArgumentNullException">Arg cannot be null <paramref name="arg"/></exception>`
4. `<exception cref="ArgumentNullException">Thrown when <paramref name="arg"/> is <see langword="null"/></exception>`

Agree?
