### ISSUE TITLE
Exceptional working correctly with C# exception filters.

### ISSUE THREAD

**Issue by WilbertOnGithub** [CSharpAnalyzers/ExceptionalReSharper#28]
Consider the following bit of code:

```c#
try
{
	if (soundFile.PlaySync)
	{
		// ReSharper disable once ExceptionNotDocumented
		player.PlaySync(); // Block thread while playing sound
	}
	else
	{
		// ReSharper disable once ExceptionNotDocumented
		player.Play(); // Play asynchronously
	}
}
// ReSharper disable once CatchAllClause
catch (Exception ex) when (ex is FileNotFoundException || 
						   ex is InvalidOperationException || 
						   ex is TimeoutException)
{
	log.LogFormat(Level.Error, "Error occurred while trying to play sound. Exception: {0}", ex);
}
```

Exceptional now gives warnings about not catching the specific exceptions that could be thrown by PlaySync and Play. However, I am catching those specific exceptions using the exception filter.

It would be nice if Exceptional detected this and would not give me those warnings.

**Comment by rsuter** [comment]
This one is hard because the filter may be a complex boolean expression and determining the filtered types may not be possible (the halting problem)

**Comment by WilbertOnGithub** [comment]
Correct.

Might be an option to generate a different text for the warning if we
detect that an exception filter is used?

Met vriendelijke groet / kind regards,

Wilbert van Dolleweerd


2015-12-22 10:09 GMT+01:00 Rico Suter <notifications@github.com>:

**Comment by pedromagueija** [comment]
@WilbertOnGithub could you test with the latest version (2016.2)? I believe this issue has been addressed.

Thanks.

**Comment by rsuter** [comment]
Yes, I think this is implemented in the newest version... please check and report back

**Comment by WilbertOnGithub** [comment]
```
            string s = "666";
            try
            {
                int i = Convert.ToInt32(s);

            }
            catch (Exception ex) when (ex is OverflowException) 
            {
                //throw;
            }
```

Just tried the following code. Plugin now longer gives a a warning about catching all exceptions. Looks like it is working.

Good job everyone! Closing this issue.

**Comment by garrett4** [comment]
I'm still having this problem in version 0.18.
