### ISSUE TITLE
Mispelling in exception warning disable comment.

### ISSUE THREAD

**Issue by wiredwiz** [CSharpAnalyzers/ExceptionalReSharper#29]
The comment 
`// ReSharper disable once VirtualMemberCallInContructor`
is spelled incorrectly.  It should instead read
`// ReSharper disable once VirtualMemberCallInConstructor`

**Comment by pedromagueija** [comment]
@wiredwiz Are you sure this is caused by 'Exceptional'? I couldn't find any reference to 'VirtualMemberCallInContructor' in the code.

'Resharper' itself does have a 'Virtual member call in constructor' inspection.

**Comment by wiredwiz** [comment]
Ah perhaps it is an issue in Resharper itself then.  I will try to replicate this now and see if it is spelled correctly.

**Comment by wiredwiz** [comment]
Yes it has indeed been fixed, it must have been a bug in ReSharper that was since corrected.  Apologies for the miss-attribution.
