### ISSUE TITLE
Exceptional warnings show despite // ReSharper disable // [SuppressMessage]

### ISSUE THREAD

**Issue by BenHamel** [CSharpAnalyzers/ExceptionalReSharper#37]
Exceptional warnings are showing even if i use any number of comments to disable them.
Nothing works:

// ReSharper disable All

// ReSharper disable once ExceptionNotDocumented

// ReSharper disable ExceptionNotDocumented

[SuppressMessage("ReSharper", "ExceptionNotDocumented")]

The only things I can do to get the warnings to disappear are catch the exception or document it, there is no way to suppress it.

**Comment by rip327** [comment]
Is anyone looking at this issue? This used to work but has now been broken for several months.

**Comment by kroniak** [comment]
Agree, I have to delete this extension. Please fix.

**Comment by wiredwiz** [comment]
Yes, this is incredibly annoying and makes the extension less useful.  Please fix this.

**Comment by pedromagueija** [comment]
I find it odd that Resharper itself does not handle this. I can hide the "hint" using code that checks if a comment is present in the previous line (for the "once" case). 

Is this the correct way to go @rsuter?

**Comment by rsuter** [comment]
I hoped that R# handles that for us, and we don't have to analyze this comment our self... But it seems that we have to handle this internally... Can you implement this? Are you interested in helping here?

I currently don't have to work on this project, but I will release new versions to the gallery...

**Comment by pedromagueija** [comment]
I also thought so (https://stackoverflow.com/questions/40016739/suppress-resharper-highlight). Let's see if someone has an idea. 

I'll help around here and there if you don't mind. I'm set on this issue because it's also affecting me.
Is there any kind of documentation or overview of how the project itself is structured?

**Comment by rsuter** [comment]
Maybe @citizenmatt can help us?

**Comment by citizenmatt** [comment]
It's dead easy, but I can't quite remember off the top of my head. If the phrase "Use the other implementation of the highlighting consumer in the daemon" means anything to you, then I think that's it :)

I'll dig it out and write it up probably tomorrow (got a big piece of work on right now).

**Comment by pedromagueija** [comment]
@citizenmatt Thanks for the pointer, I'll look it up and see that I can find. I'd be much appreciated if you could leave your notes when you have some spare time. Thanks again.

**Comment by pedromagueija** [comment]
@citizenmatt Found your posted solution at https://resharper-support.jetbrains.com/hc/en-us/community/posts/206559159-10-1-EAP-and-RegisterConfigurableSeverity?flash_digest=1939ba6f66e30d494edb8f0d6a902eab4b198342

Works just fine 👍 

Thanks again

**Comment by citizenmatt** [comment]
Nice! I should have just written that into the dev guide 🙃

**Comment by CodeSingularity** [comment]
Thanks everyone for your help in resolving this! 

looking forward to the next nuget release so I can use Exceptional again

**Comment by rsuter** [comment]
Release v0.7.13

**Comment by rsuter** [comment]
If someone is interested in maintaining and developing this project, please contact me...
