### ISSUE TITLE
Add Package Build for ReSharper 2016.2

### ISSUE THREAD

**Issue by jongleur1983** [CSharpAnalyzers/ExceptionalReSharper#38]
Finally I figured out how to get my local changes to be installable in Resharper 2016.2, but it took a while unfortunately.

For now and for me locally I just copied the nuspec file for 2016.1 and changed the required wave to include up to 7.0 (=> 2016.2) which seems to work, but I don't know if that's sufficient.

In which way does Exceptional require a minimum ReSharper version for single functions yet? is it really necessary to use separate projects, or could it be simplified and just built for different targets?

In any case I would appreciate an up to date how-to about how to contribute (including how to build and test locally as that was a major part of what I tried to do).

Update: it's not sufficient as far as I can see: 
Looks like the jetbrains references have to be upgraded as well.

Given that: Is there a reason why ReSharper 2016.2 is published in the resharper plugin repository, but not yet included in this project?

**Comment by rsuter** [comment]
It seems that they always change the apis from version to version and thus we need a nuget per version. Currently its not that big a problem because we can reference the same files in each project and use compiler flags... 

Dubugging is a whole different story. In the first versions it was possible to start the extension in a dubuggable vs instance... With the recent resharper version i could not find such a solution. Maybe this is fixed now? 

I'd really appreciate help in this project because i currently do not have the time to work on it...

**Comment by jongleur1983** [comment]
great to get an answer ;) Do you know where the 2016.2 package in the resharper repository comes from? Did you publish it? Don't want to shoulder to get the next version working/building in Visual Studio if it's not necessary.

**Comment by rsuter** [comment]
I think the visibility is controlled by the wave version (see packages.config)

**Comment by rsuter** [comment]
@jongleur1983 I don't know who published the 2016.2 version! It is not from me and thus not "official"... I contacted the publisher, but I didn't receive an answer yet...

**Comment by rsuter** [comment]
So it's not your package?

**Comment by jongleur1983** [comment]
no, it's not.

**Comment by rsuter** [comment]
I think its from @lotosbin, check the Git network...

**Comment by pedromagueija** [comment]
@rsuter debugging now has to be done by copying the dll's into a hive instance.
https://github.com/JetBrains/resharper-devguide/issues/14

I'd also love to have an official 2016.2 version.

**Comment by rsuter** [comment]
Ok, official packages have been published. 

https://github.com/CSharpAnalyzers/ExceptionalReSharper/commit/dd5ceacbee70b8d71b4b756c68fafc087ce96a57

v0.7.11

**Comment by rsuter** [comment]
Needed a fix in the wave version, v0.7.12
Please report any problems..
