### ISSUE TITLE
Trouble  updating Exceptional to 2016.2

### ISSUE THREAD

**Issue by pshrosbree** [CSharpAnalyzers/ExceptionalReSharper#42]
I'd appreciate any help getting around the following error when attempting to update Exceptional (using the extensions gallery in R# 2016.2):

`Error registering mapping for catalog assembly “ReSharper.Exceptional.2016.2, Version=0.7.8.0, Culture=neutral, PublicKeyToken=null”. An item with the same key has already been added.
An item with the same key has already been added.
Execute Build Step Runnable JetBrains.Platform.VisualStudio.Core!JetBrains.VsIntegration.UI.WindowManagement.Install.VsPackageEmitsToolWindowIcons::CollectToolWindowIcons#3 has failed. The build step method JetBrains.VsIntegration.UI.WindowManagement.Install.VsPackageEmitsToolWindowIcons::CollectToolWindowIcons has thrown an exception. Exception has been thrown by the target of an invocation. An item with the same key has already been added.
Cannot index assemblies in the application packages. There are at least two assemblies with the same simple name “ReSharper.Exceptional.2016.2, Version=0.7.8.0, Culture=neutral, PublicKeyToken=null” in packages Exceptional.2016.2 and Binbin.Exceptional.2016.2. An item with the same key has already been added.`

[Install log](https://github.com/CSharpAnalyzers/ExceptionalReSharper/files/536449/InstallerLog012.txt)

**Comment by pedromagueija** [comment]
Perhaps it's nothing but did you have the Unofficial Exceptional package installed? Did you remove it before installing the official one?

**Comment by pedromagueija** [comment]
@pshrosbree we're closing the issue now, but if you still face it please let us know.
Thanks.
