### ISSUE TITLE
Documentation warnings do not support Exception hierarchy

### ISSUE THREAD

**Issue by rwv37** [CSharpAnalyzers/ExceptionalReSharper#46]
If you throw some sort of exception, and document the method as throwing a base type of that exception's type, you'll get two inappropriate errors from Exceptional.  For example, in the following,

(1) Task.Delay() can throw a TaskCanceledException;
(2) A TaskCanceledException is an OperationCanceledException;
(3) The method is documented as throwing OperationCanceledException

... and yet Exceptional gives the following seemingly inappropriate messages:

(1) Exception 'OperationCanceledException' is not thrown
(2) Exception 'TaskCanceledException' is not documented

```
    /// <summary>
    /// The blah async.
    /// </summary>
    /// <param name="cancellationToken">
    /// The cancellation token.
    /// </param>
    /// <returns>
    /// The <see cref="Task"/>.
    /// </returns>
    /// <exception cref="OperationCanceledException">
    /// The operation was canceled.
    /// </exception>
    public async Task BlahAsync(CancellationToken cancellationToken)
    {
        await Task.Delay(37, cancellationToken).ConfigureAwait(false);
    }
```

**Comment by pedromagueija** [comment]
There is an option in settings that allow for base types to suffice as documented exceptions:

Resharper -> Options -> Exception -> General tab -> Documentation of thrown exception's subtype is sufficient

Mark both checkboxes and then make a change in the file and save.

**Comment by rwv37** [comment]
Great. Thank you!
