### ISSUE TITLE
Exceptional for 2016.3

### ISSUE THREAD

**Issue by kirbatious** [CSharpAnalyzers/ExceptionalReSharper#50]
Any idea when Exceptional will be out for the latest Resharper release 2016.3? I miss it already!

**Comment by janmohammadi** [comment]
same problem! please release 2016.3 compatible version.

**Comment by borismod** [comment]
Is there any estimates for the 2016.3 compatible plugin? I might downgrade the R# otherwise

**Comment by rsuter** [comment]
I think this shouldnt be a big effort ..

**Comment by CADbloke** [comment]
> I think this shouldnt be a big effort ..

Then fork it and try it. I tried for a couple of hours and I couldn't get the Nuget dependencies right. Your turn, because that's how open source works. 

Ahem: #35

**Comment by rsuter** [comment]
It seems that we cannot release a new version for R# 2016.3 because of this problem... @pedromagueija and me are trying to create the project but we cannot upgrade the NuGet packages.

@citizenmatt: Can you have a look at this?

**Comment by kirbatious** [comment]
Thanks for your efforts so far, guys! The Youtrack issue submitted by @borismod has been bumped up to Critical by Jetbrains, so hopefully they'll sort it out soon

**Comment by citizenmatt** [comment]
Just seen this, replied on the issue. I think it's because you're a .net 4.0 class library, and you now need to be .net 4.5. Update framework version, reinstall existing packages, then update to latest SDK. That should do it.

**Comment by pedromagueija** [comment]
@citizenmatt Hi Matt,
I've finally installed the new SDK and Wave, but now I'm having an issue with API changes.

- ICatchVariableDeclaration no longer has a SetDeclaredTypeUsage method
- IReferenceExpressionReference no longer has a CurrentResolveResult property
- ICatchClause no longer contains has a ConditionClause property

Are these documented somewhere that I can use to adjust the code to the new API?
As always, thanks for your help

**Comment by derigel23** [comment]
@pedromagueija about IReferenceExpressionReference.CurrentResolveResult - you should never use it, it's internal property. Invoke Resolve() to get result.

**Comment by pedromagueija** [comment]
@derigel23 Thanks for the tip. I've replaced the call to CurrentResolveResult with Resolve();

**Comment by rsuter** [comment]
v0.8.0.0 is now pushed to the extension gallery. Please try if everything works for you...
