### ISSUE TITLE
Add support for R# 2017.1

### ISSUE THREAD

**Issue by cmeeren** [CSharpAnalyzers/ExceptionalReSharper#52]
Are you planning on implementing support for R# 2017.1?

Please do, this is a fantastic plugin which I really need! 😅

**Comment by sharethl** [comment]
with resharper 2016.3, it shows two exceptional resharper plugins
1. exceptional for resharper 2016.3
2. exceptional for resharper 2017.1

**Comment by cmeeren** [comment]
@sharethl weird, I'm using R#2017.1.2 and can't find this plugin at all.

**Comment by Hirato** [comment]
I suspect it's that the 2017.1 package restricts the compatible version of wave such that `7.0 <= version < 8` must be true. 

the 2016.3 package has the exact same constraint, so those R# users end up seeing both, and we see neither.

**Comment by cmeeren** [comment]
@RSuter should be a very quick fix, then?

**Comment by pedromagueija** [comment]
I'll have some time this Sunday to look at this. Hopefully, by Monday a new version will be available.

**Comment by pedromagueija** [comment]
Hi guys, I'm struggling with an issue regarding Visual Studio 2017. I've managed to update the Resharper SDK on an older VS version though.

Sorry for the delay but I'm working on it.
Cheers.

**Comment by cmeeren** [comment]
Hi @pedromagueija, how are things progressing? Do you need any assistance?

**Comment by pedromagueija** [comment]
Hey guys,

In the last "episode" I was able to update the Resharper SDK using VS2015. Today I've managed to get it to compile (good news).

I'll test on my environment, just to make sure nothing is awfully broken.
If everything goes well, I'll commit the update today.

On a side note, I think it would be best to unify the several projects in this solution. Currently, there are several projects all "linked" together, and that makes it hard to update. I'll investigate this possibility but any feedback or suggestions on this will be appreciated.

**Comment by pedromagueija** [comment]
Unfortunately, it's not working for me. I can't install it.

In the Experimental Instance of Visual Studio, it launches the plugin "installer" and asks to restart VS. But then nothing.

**Comment by cmeeren** [comment]
I can test it, but I'd need full instructions - I've never developed a VS extension before.

**Comment by firehirsch** [comment]
Is it really so complicated to add compatibility to 2017.1?
Looks like no one is really caring about this Project

**Comment by olsh** [comment]
Hey folks,

I've just added support for R# 2017.1 in the PR #55  (_only simple smoke tests were run_)
You can download the compiled package here
https://github.com/olsh/ExceptionalReSharper/blob/4753fa3532a587b047cb1f5dc47982b5be1d8b33/build/Packages/Exceptional.2017.1.0.8.0.0.nupkg

**Comment by pedromagueija** [comment]
@olsh This is great news. I'll try it out as soon as I can.

**Comment by RSuter** [comment]
I'm just looking into it...

**Comment by RSuter** [comment]
https://resharper-plugins.jetbrains.com/packages/ExceptionalDevs.Exceptional/0.9.0

**Comment by cmeeren** [comment]
I see two plugins in the list now, is that intentional?

![exceptional](https://user-images.githubusercontent.com/7766733/27420602-ed37c068-5726-11e7-9d05-3036b4507a0e.png)

**Comment by RSuter** [comment]
Nope, ill unlist the old one...

**Comment by RSuter** [comment]
ok, now it's only one

**Comment by cmeeren** [comment]
Thanks! Installing now.

**Comment by RSuter** [comment]
Ok, works for me... I'll remove all old project - i think its simpler to support just the latest R# version in the future...

**Comment by pedromagueija** [comment]
It's also working for me. This is brilliant.

**Comment by RSuter** [comment]
BTW: If someone is interested in doing a completely rewrite of this extension with Roslyn (to be R# independent), I started the project: https://github.com/CSharpAnalyzers/ExceptionalAnalyzers

(but i don't have the time to work on it :-)

**Comment by firehirsch** [comment]
I think a complete recoding is not necessary. It would be enough if you cleanup this codebase.
If you want some help with that, mybe I could help you.

**Comment by pedromagueija** [comment]
@firehirsch I think all help would be welcome.

**Comment by RSuter** [comment]
Yes, there are still a lot of open issues/feature request - we should mostly concentrate on those which relate to the new C# versions
