### ISSUE TITLE
Exceptional missing from Resharper extensions in version 2017.3.1

### ISSUE THREAD

**Issue by rolandh** [CSharpAnalyzers/ExceptionalReSharper#69]
Can no longer download exceptional in version 2017.3.1

![image](https://user-images.githubusercontent.com/1109554/35026737-b3719b72-fb9c-11e7-803a-fa245330ae0e.png)

**Comment by RSuter** [comment]
See https://github.com/CSharpAnalyzers/ExceptionalReSharper/pull/68/files

**Comment by RSuter** [comment]
v0.12.0 released: https://resharper-plugins.jetbrains.com/packages/ExceptionalDevs.Exceptional/0.12.0
