### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by volvo-martin** [CSharpAnalyzers/ExceptionalReSharper#75]
Using Visual Studio 2017 and ReSharper 2018.1
Changing the Exceptional settings and then trying to save -- nothing is saved

**Comment by Zero3** [comment]
I can confirm this issue, though only for the General tab. Changes to the other tabs seems to work fine.

**Comment by ivanstus** [comment]
Same here

**Comment by mu88** [comment]
Are there any workarounds?
