### ISSUE TITLE
Update to Resharper 2018.2

### ISSUE THREAD

**Issue by elmanav** [CSharpAnalyzers/ExceptionalReSharper#77]
Please update to Resharper 2018.2.
Thanks.

**Comment by kakalaky** [comment]
#78

**Comment by RSuter** [comment]
=> https://resharper-plugins.jetbrains.com/packages/ExceptionalDevs.Exceptional/0.14.0

**Comment by RSuter** [comment]
@kakalaky thanks for the PR!

**Comment by RSuter** [comment]
Please test and report here if everything is fine.

**Comment by elmanav** [comment]
Very nice! 👍
