### ISSUE TITLE
Resharper 2018.3 support

### ISSUE THREAD

**Issue by PetyrBaelish** [CSharpAnalyzers/ExceptionalReSharper#82]
Apparently this package is not available for download via Resharper -> Extension Manager. Please, update to the latest version of Resharper.

_Resharper: 2018.3
Visual Studio:  15.9.28307.222_ #

**Comment by RSuter** [comment]
Can you check whether the new version works?

https://resharper-plugins.jetbrains.com/packages/ExceptionalDevs.Exceptional/0.15.0

**Comment by kakalaky** [comment]
Looks like it needs the wave dependency that was removed from the nuspec to show up for 2018.3.
<dependency id="Wave" version="[183.0.0]" />

**Comment by RSuter** [comment]
Are you sure? This package is deprecated: 

https://www.nuget.org/packages/Wave

**Comment by kakalaky** [comment]
It shows up in the extension manager now so I'm going with yes, the dependency is needed. Per the dev guide at https://www.jetbrains.com/help/resharper/sdk/Extensions/Packaging.html it is still needed as well. Looks like wave isn't a real package anymore and is only used to indicate which package feed it should be visible on.

Seems to be working fine so far. Thanks for the update.
