### ISSUE TITLE
Save problem with Checkboxes in Options 

### ISSUE THREAD

**Issue by matzew01** [CSharpAnalyzers/ExceptionalReSharper#88]
I have a newly-built Visual Studio Professional 2017 with ReShaprer Ultimate and Exceptional. I have the problem that in Options the checkboxes of Exceptional are not saved. The textareas were saved. Even if I insert the entries manually into the settings file and restart, the entries are not taken over. The checkboxes of other extensions and the ReSharper included ones were saved.

**Comment by matzew01** [comment]
I wrote to fast, problem is mentioned here: https://github.com/CSharpAnalyzers/ExceptionalReSharper/issues/75
Sorry for the double post. My description is a bit more accurate I think, so I leave the post open.

**Comment by RicoSuter** [comment]
I’m not actively improving this extension as i no longer use R#.. happy to accept PRs and publish updates.

**Comment by ManticSic** [comment]
See #75
