### ISSUE TITLE
Exceptional not available in Extension Manager

### ISSUE THREAD

**Issue by HelenAvelin** [CSharpAnalyzers/ExceptionalReSharper#89]
I am running VS2019 and ReSharper 2019.2

**Comment by rolandh** [comment]
I find this is regularly an issue, resharper is updated almost weekly at some stages so it means 75% of the time I cannot use exceptional as your releases lag theirs. Is there anyway we can automate exceptional being ready for the new resharper releases?

**Comment by ManticSic** [comment]
@patrickweegen and I have taken over the maintenance of this project (See #92). We hope to get rid of the huge delay.
