### ISSUE TITLE
2019.2.x Support?

### ISSUE THREAD

**Issue by Mike-EEE** [CSharpAnalyzers/ExceptionalReSharper#91]
IT'S THAT TIME AGAIN!!! 😁

I am currently employing 13 R# extensions and only two of them have not made the jump over yet to 2019.2 (the other being https://github.com/hmemcpy/ReSharper.InternalsVisibleTo/issues/14).

**Comment by patrickweegen** [comment]
I have the exact same problem, and it's realy frustrating since I rellay heavily on this extenstion.

**Comment by RicoSuter** [comment]
This pr?
https://github.com/CSharpAnalyzers/ExceptionalReSharper/pull/90

Can you review?

**Comment by Mike-EEE** [comment]
Cool @RicoSuter that seems promising.  I am not sure I can review it, however.  As I am simply a lowly user, my knowledge and skillset can only go as far as nagging repo owners for new version deployments. 😆  

Even still, I am not familiar enough with R#'s plugin system to make definitive judgments on whether something is sufficiently configured and adjusted to deploy for production use under the latest SDKs... apologies if I misunderstood you!

**Comment by Mike-EEE** [comment]
Now that `InternalsVisibleTo` [has been deployed](https://github.com/hmemcpy/ReSharper.InternalsVisibleTo/issues/14#issuecomment-544462578), this is the last and **only** remaining plugin out of _thirteen_ that I use that is not available to 2019.2.x.  

Just sayin'. 😁 😭

**Comment by ManticSic** [comment]
Any progress on this topic? I'm currently using rudidlo update ( #90 ), but it would be great to get it from an official source...

**Comment by Mike-EEE** [comment]
I am thinking we need should make an `ExceptionalReSharper.Unofficial` somewhere since it appears this the official source is dying/despondent. 😞

**Comment by ManticSic** [comment]
In issue #92 I asked if a new maintainer is searched, to provide official builds.

**Comment by RicoSuter** [comment]
Sorry guys, i hope to find time to release it today. But as i no longer use R# i’d be happy to find a new maintainer

**Comment by RicoSuter** [comment]
New version has been uploaded and is being reviewed.

**Comment by Mike-EEE** [comment]
Thank you @RicoSuter!  Sounds like @patrickweegen is interested in taking over.  Anything that results in less than two months of waiting is fine by me. 😁

**Comment by patrickweegen** [comment]
Would be my first R#-Extension, but with a little help from the community I could try to take over.

**Comment by ManticSic** [comment]
Maybe more as one maintainer would be usefull.... even if this is a small project

**Comment by patrickweegen** [comment]
@ManticSic Would be very good if there were more maintainers than one alone.
But maybe we should discuss this in #92

**Comment by ManticSic** [comment]
Thanks @rudidlo for PR #90
