### ISSUE TITLE
New Maintainer?

### ISSUE THREAD

**Issue by ManticSic** [CSharpAnalyzers/ExceptionalReSharper#92]
In #88 you said, that you no longer actively maintain this extension. Do you search a new maintainer for this extension, so a official build can be created?

**Comment by patrickweegen** [comment]
I think many of the people who commented on the last issues would be happy if a new maintainer would take over.
I really miss the functionality of this extension and would participate in maintaining this extension further.

**Comment by RicoSuter** [comment]
If someone wants to take over, i’ll give him access to the repo and the r# plugin repository. I will keep access rights if there’s a problem, etc.

**Comment by chris-dd** [comment]
I would love to assist with maintaining the plugin.

**Comment by ManticSic** [comment]
Me too, but I'm limited in time.

So there are three person who are interested in maintaining or helping to maintain this project....

It would be a shame if this extension dies...

**Comment by ManticSic** [comment]
@patrickweegen and I are nor maintainer.
Thanks @RicoSuter
